# Generated by Django 5.2.7 on 2025-10-25 07:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_crypto", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("precision", models.PositiveIntegerField(default=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "currencies",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="TradingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                (
                    "market_type",
                    models.CharField(
                        choices=[("spot", "Spot"), ("futures", "Futures")],
                        default="spot",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "min_order_size",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                (
                    "max_order_size",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                ("price_precision", models.PositiveIntegerField(default=2)),
                ("quantity_precision", models.PositiveIntegerField(default=6)),
                (
                    "maker_fee",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.001"), max_digits=5
                    ),
                ),
                (
                    "taker_fee",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.001"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_pairs",
                        to="markets.currency",
                    ),
                ),
                (
                    "quote_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_pairs",
                        to="markets.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Pair",
                "verbose_name_plural": "Trading Pairs",
                "db_table": "trading_pairs",
                "ordering": ["symbol"],
                "unique_together": {("base_currency", "quote_currency", "market_type")},
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "volume_24h",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "change_24h",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "change_percent_24h",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "high_24h",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "low_24h",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "bid_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "ask_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "bid_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "ask_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data",
                        to="markets.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Data",
                "verbose_name_plural": "Market Data",
                "db_table": "market_data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("5m", "5 Minutes"),
                            ("15m", "15 Minutes"),
                            ("1h", "1 Hour"),
                            ("4h", "4 Hours"),
                            ("1d", "1 Day"),
                        ],
                        max_length=5,
                    ),
                ),
                ("open_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume", models.DecimalField(decimal_places=8, max_digits=20)),
                ("timestamp", models.DateTimeField()),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="markets.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price History",
                "db_table": "price_history",
                "ordering": ["-timestamp"],
                "unique_together": {("trading_pair", "interval", "timestamp")},
            },
        ),
    ]
